[
    [
        [
            "examinados",
            "vetted",
            "",
            ""
        ]
    ],
    "",
    "en",
    "",
    [
        [
            "examinados",
            [
                5
            ],
            1,
            0,
            400,
            0,
            1,
            0
        ]
    ],
    [
        [
            "vetted",
            5,
            [
                [
                    "examinados",
                    400,
                    1,
                    0
                ],
                [
                    "investigados",
                    246,
                    1,
                    0
                ],
                [
                    "examinadas",
                    154,
                    1,
                    0
                ],
                [
                    "vetados",
                    146,
                    1,
                    0
                ],
                [
                    "investigado",
                    51,
                    1,
                    0
                ]
            ],
            [
                [
                    0,
                    6
                ]
            ],
            "vetted"
        ]
    ],
    "",
    "",
    [
        [
            "en"
        ]
    ],
    2
]